### ISSUE TITLE
Invalid prop: type check failed for prop "loading". Expected Boolean, got String.

### ISSUE THREAD

**Issue by aruxek** [purocean/laravel-template#1]
Hello, I am trying to run the application, but I mark the following error when trying to access any section, could you support me?
 
The connection to http://localhost:8077/__webpack_hmr was interrupted while the page was loading.
desktop.js%20line%201445%20%3E%20eval:75:13
[Vue warn]: Invalid prop: type check failed for prop "loading". Expected Boolean, got String.

found in

---> <Table>
       <SpinWrapper> at /home/arux/gits/ollin/tototli/frontend/src/components/SpinWrapper.vue
         <DataTable> at /home/arux/gits/ollin/tototli/frontend/src/components/DataTable.vue
           <Card>
             <DesktopLayout> at /home/arux/gits/ollin/tototli/frontend/src/layouts/Desktop.vue
               <Departments> at /home/arux/gits/ollin/tototli/frontend/src/desktop/Departments.vue
                 <App> at /home/arux/gits/ollin/tototli/frontend/src/CDesktop.vue
                   <Root

**Comment by purocean** [comment]
Please check README.md
```bash
composer install
cp .env.example .env
vim ./.env # 配置数据库，企业微信，缓存等信息
php ./artisan key:generate
php ./artisan jwt:secret
php ./artisan migrate # 迁移表结构
php ./artisan rbac:resetpwd suadmin <password> # 更改超级管理员密码
php ./artisan serve --host=192.168.1.108 # 运行开发服务器，IP 为本机局域网 IP，以便手机访问（扫码）
php ./artisan queue:work # 开启任务队列进程，如果队列使用同步可以不开启
composer run-script make-api-doc # 生成接口文档

cd frontend
npm install # 安装 nodejs 依赖，建议使用yarn
cp ./config/index.js.example ./config/index.js
vim ./config/index.js # 修改本机后台服务器 IP 端口
npm run dev # 运行开发服务器
npm run build # 前端打包
npm run dist # 把打包的文件复制到 public 目录
# npm run dist-win # 把打包的文件复制到 public 目录，windows 平台使用
```
